name = "cup-radar"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cup-radar-summaries"
database_id = "32125759-8060-4011-bbe4-1fec0f649398"
